---
- name: "clean up server"
  become: true
  shell: "sudo rm -rf *"

- name: "git clone repo"
  become: true
  shell: "git clone https://github.com/Bhuvanhruday/cdond-c3-projectstarter.git"

- name: "install dependency"
  become: true
  shell: "sudo npm install"
  args:
    chdir: "/home/ubuntu/cdond-c3-projectstarter/backend"

- name: "install peers dependency"
  become: true
  shell: "sudo npm install -g npm-install-peers"
  args:
    chdir: "/home/ubuntu/cdond-c3-projectstarter/backend"

- name: "build backend server"
  become: true
  shell: "npm run build"
  args:
    chdir: "/home/ubuntu/cdond-c3-projectstarter/backend"

- name: "install nodejs."
  become: true
  apt:
    name: ["nodejs", "npm", "net-tools"]
    state: latest
    update_cache: yes

- name: "run backend server"
  become: true
  shell: "pm2 start npm --name 'udapeople' -- start"
  args:
    chdir: "/home/ubuntu/cdond-c3-projectstarter/backend"
  async: 45
  poll: 0